spring:
  application:
    name: search-service
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  thymeleaf:
    cache: false
  redis:
    host: redis-server
    port: 6379
  session:
    store-type: redis

  # 服务追踪发现
  zipkin:
    base-url: http://zipkin-server:9411/
    # 关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false
# 开启debug日志
log:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

server:
  port: 12000